# dict of character aliases and corresponding character ID
aliases = {
    "mario": 0,
    "mar": 0,
    "luigi": 1,
    "weegee": 1,
    "lu": 1,
    "dk": 2,
    "donkeykong": 2,
    "diddy": 3,
    "diddykong": 3,
    "peach": 4,
    "daisy": 5,
    "yoshi": 6,
    "yosh": 6,
    "babymario": 7,
    "bmario": 7,
    "bluigi": 8,
    "babyluigi": 8,
    "bowser": 9,
    "bow": 9,
    "wario": 10,
    "waluigi": 11,
    "walu": 11,
    "koopa(g)": 12,
    "gkoopa": 12,
    "greenkoopa": 12,
    "greenkoopatroopa": 12,
    "greg": 12,
    "koopa": 12,
    "koopatroopa": 12,
    "toad(r)": 13,
    "rtoad": 13,
    "toadred": 13,
    "redtoad": 13,
    "toad": 13,
    "boo": 14,
    "toadette": 15,
    "tdette": 15,
    "pigtails": 15,
    "shyguy(r)": 16,
    "shyguyred": 16,
    "redshyguy": 16,
    "redguy": 16,
    "rsg": 16,
    "shyguy": 16,
    "birdo": 17,
    "pigglywiggly": 17,
    "monty": 18,
    "montymole": 18,
    "moonball": 18,
    "bowserjr": 19,
    "bj": 19,
    "bowserjunior": 19,
    "jr": 19,
    "sux": 19,
    "paratroopa(r)": 20,
    "koopaparatroopared": 20,
    "redkoopaparatroopa": 20,
    "parared": 20,
    "redpara": 20,
    "rpara": 20,
    "ptred": 20,
    "redpt": 20,
    "paratroopa" : 20,
    "koopaparatroopa" : 20,
    "pianta(b)": 21,
    "piantablue": 21,
    "bluepianta": 21,
    "bpianta": 21,
    "blueblob": 21,
    "bb": 21,
    "blob": 21,
    "pianta(r)": 22,
    "piantared": 22,
    "redpianta": 22,
    "pm": 22,
    "rpianta": 22,
    "pianta": 22,
    "pianta(y)": 23,
    "piantayellow": 23,
    "yellowpianta": 23,
    "yellafella": 23,
    "yellowfellow": 23,
    "yf": 23,
    "ypianta": 23,
    "yifdaddy" : 23,
    "noki(b)": 24,
    "nokiblue": 24,
    "bluenoki": 24,
    "boki": 24,
    "bnoki": 24,
    "bnoke": 24,
    "noki(r)": 25,
    "nokired": 25,
    "rednoki": 25,
    "noki": 26,
    "gnoki": 26,
    "noki(g)": 26,
    "nokigreen": 26,
    "greennoki": 26,
    "mintnoki": 26,
    "gnoke": 26,
    "gnocchi": 26,
    "bro(h)": 27,
    "hammerbro": 27,
    "hammer": 27,
    "h!bro": 27,
    "hbro": 27,
    "toadsworth": 28,
    "tw": 28,
    "peterose": 28,
    "oldman": 28,
    "toad(b)": 29,
    "toadblue": 29,
    "bluetoad": 29,
    "btoad": 29,
    "teardrop": 29,
    "toad(y)": 30,
    "toadyellow": 30,
    "yellowtoad": 30,
    "peetoad": 30,
    "cornpop": 30,
    "toad(g)": 31,
    "toadgreen": 31,
    "greentoad": 31,
    "gtoad": 31,
    "toad(p)": 32,
    "toadpurple": 32,
    "purpletoad": 32,
    "leantoad": 32,
    "ptoad": 32,
    "magikoopa(b)": 33,
    "magikoopablue": 33,
    "bluemagikoopa": 33,
    "magblue": 33,
    "mag": 33,
    "bluemag": 33,
    "mageblue": 33,
    "bluemage": 33,
    "bmage": 33,
    "bmag": 33,
    "magikoopa(r)": 34,
    "magikoopared": 34,
    "redmagikoopa": 34,
    "magred": 34,
    "redmag": 34,
    "magered": 34,
    "redmage": 34,
    "rmag": 34,
    "rmage": 34,
    "magikoopa(g)": 35,
    "magikoopagreen": 35,
    "greenmagikoopa": 35,
    "maggreen": 35,
    "greenmag": 35,
    "magegreen": 35,
    "greenmage": 35,
    "gmag": 35,
    "gmage": 35,
    "magikoopa(y)": 36,
    "magikoopayellow": 36,
    "yellowmagikoopa": 36,
    "magyellow": 36,
    "yellowmag": 36,
    "mageyellow": 36,
    "yellowmage": 36,
    "pisswizard": 36,
    "pisswizz": 36,
    "pizzwizz": 36,
    "weezard": 36,
    "ymag": 36,
    "kingboo": 37,
    "kboo": 37,
    "kb": 37,
    "peteypiranha": 38,
    "petey": 38,
    "peaty": 38,
    "peety": 38,
    "peter": 38,
    "dixiekong": 39,
    "dixie": 39,
    "dix": 39,
    "goomba": 40,
    "goombo": 40,
    "dingus": 40,
    "goobna": 40,
    "paragoomba": 41,
    "wingombo": 41,
    "parag": 41,
    "pg": 41,
    "fpt": 41,
    "koopa(r)": 42,
    "koopa": 42,
    "koopatroopa": 42,
    "redkoopa": 42,
    "redkoopatroopa": 42,
    "koopared": 42,
    "koopatroopared": 42,
    "rkoopa": 42,
    "rafa": 42,
    "rafael": 42,
    "ron": 42,
    "ronald": 42,
    "rkoopa": 42,
    "paratroopa(g)": 43,
    "koopaparatroopagreen": 43,
    "greenkoopaparatroopa": 43,
    "paragreen": 43,
    "greenpara": 43,
    "ptgreen": 43,
    "greenpt": 43,
    "para": 43,
    "parat": 43,
    "pt": 43,
    "gpara": 43,
    "shyguy(b)": 44,
    "shyguyblue": 44,
    "blueshyguy": 44,
    "blueguy": 44,
    "bsg": 44,
    "bshyguy": 44,
    "shyguy(y)": 45,
    "shyguyyellow": 45,
    "blueshyyellow": 45,
    "yellowguy": 45,
    "ysg": 45,
    "yshyguy": 45,
    "shyguy(g)": 46,
    "shyguygreen": 46,
    "greenshyguy": 46,
    "greenguy": 46,
    "gsg": 46,
    "gshyguy": 46,
    "shyguy(bk)": 47,
    "shyguyblack": 47,
    "blackshyguy": 47,
    "blackguy": 47,
    "blsg": 47,
    "blshyguy": 47,
    "drybones(gy)": 48,
    "drybones": 48,
    "drybonesgray": 48,
    "drybonesgrey": 48,
    "greydrybones": 48,
    "graydrybones": 48,
    "bonesgray": 48,
    "bonesgrey": 48,
    "greybones": 48,
    "graybones": 48,
    "barebones": 48,
    "drybones(g)": 49,
    "drybonesgreen": 49,
    "greendrybones": 49,
    "bonesgreen": 49,
    "greenbones": 49,
    "gbones": 49,
    "bones": 49,
    "drybones(r)": 50,
    "drybonesred": 50,
    "reddrybones": 50,
    "bonesred": 50,
    "redbones": 50,
    "rbones": 50,
    "drybones(b)": 51,
    "drybonesblue": 51,
    "bluedrybones": 51,
    "bonesblue": 51,
    "bluebones": 51,
    "bbones": 51,
    "bro(f)": 52,
    "fire": 52,
    "firebro": 52,
    "f!bro": 52,
    "fbro": 52,
    "bro(b)": 53,
    "boomerbro": 53,
    "boomer": 53,
    "b!bro": 53,
    "bbro": 53,
    "wildsr" : 54,
    "wildsuperrare": 54,
    "wildur" : 55,
    "wildultrarare" : 55,
    "bowsercastle" : 56,
    "castle" : 56,
    "dkjungle" : 57,
    "donkeykongjungle" : 57,
    "jungle" : 57,
    "mariostadium" : 58,
    "marios" : 58,
    "peachgaden" : 59,
    "peachsgarden" : 59,
    "garden" : 59,
    "toyfield" : 60,
    "tf" : 60,
    "wariopalace" : 61,
    "palace" : 61,
    "yoshipark" : 62,
    "park" : 62,
    "commonstar" : 63,
    "rarestar" : 64,
    "secretstar" : 65,
    "superstar" : 66,
    "ultrastar" : 67,
    "extrapack" : 68,
    "reroll" : 69,
    "trade" : 70,
    "missedstar" : 71,
    "missedstarchance" :71
}

def get_card_id(card):
    return aliases.get(card, None)    