name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-python:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      token: ${{ secrets.DISCORD_BOT_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          pip install requests discord.py
          python main/MSSBPackBot.py
  